#!/bin/bash
ime_fajla=$1
sudo cp /home/amar/Documents/VSProjects/WT\ spirala/wt21p18752/view/nastavnik/$ime_fajla.html /var/www/html
sudo cp /home/amar/Documents/VSProjects/WT\ spirala/wt21p18752/view/nastavnik/$ime_fajla.css /var/www/html
galen check z1Desktop.gspec --url http://localhost/$ime_fajla.html --size 1024x768 --htmlreport izvjestaji
